// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mvC
arma::vec mvC(const arma::mat& inmat, const arma::vec& invect);
RcppExport SEXP _aMSE_mvC(SEXP inmatSEXP, SEXP invectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type inmat(inmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type invect(invectSEXP);
    rcpp_result_gen = Rcpp::wrap(mvC(inmat, invect));
    return rcpp_result_gen;
END_RCPP
}
// invC
arma::mat invC(const arma::mat& x);
RcppExport SEXP _aMSE_invC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(invC(x));
    return rcpp_result_gen;
END_RCPP
}
// svvC
double svvC(const arma::vec lhs, const arma::vec rhs);
RcppExport SEXP _aMSE_svvC(SEXP lhsSEXP, SEXP rhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type lhs(lhsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type rhs(rhsSEXP);
    rcpp_result_gen = Rcpp::wrap(svvC(lhs, rhs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aMSE_mvC", (DL_FUNC) &_aMSE_mvC, 2},
    {"_aMSE_invC", (DL_FUNC) &_aMSE_invC, 1},
    {"_aMSE_svvC", (DL_FUNC) &_aMSE_svvC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aMSE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
