# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title invC matrix inversion using RcppArmadillo
#'
#' @description invC uses BLAS to conduct a matrix inversion and
#'     appears to be about 73 percent faster than R's solve when used
#'     in a length-based model context.
#'
#' @param x the matrix to be inverted
#'
#' @export
invC <- function(x) {
    .Call(`_aMSE_invC`, x)
}

#' @title mvC matrix vector product using RcppArmadillo
#'
#' @description mvC multiple the vector rhs by the matrix lhs, which
#'     is used all the time in a length-based stock assessment model.
#'     mvC appears to be 25 percent faster than R's inmat X invect
#'     when used in a length-based model context.
#'
#' @param inmat the matrix, usualy the growth transition matrix
#' @param invect the vector to be multiplied. Usually the numbers-at-
#'     size in a length based model
#' @export
mvC <- function(inmat, invect) {
    .Call(`_aMSE_mvC`, inmat, invect)
}

#' @title svvC sum of two multiplied vectors using RcppArmadillo
#'
#' @description svvC multiple the vector rhs by the vector lhs and
#'     sums the resulting vector.
#'
#' @param lhs the first vector, possibly numbers at size
#' @param rhs the second vector, possibly maturity x weight-at-length
#' @export
svvC <- function(lhs, rhs) {
    .Call(`_aMSE_svvC`, lhs, rhs)
}

